from flask import Blueprint, request, jsonify
from datetime import datetime
import json
import re

student_ai_bp = Blueprint('student_ai', __name__)

# Text Summarizer Routes
@student_ai_bp.route('/ai-tools/text-summary', methods=['POST'])
def generate_text_summary():
    try:
        data = request.get_json()
        text = data.get('text', '')
        length = data.get('length', 'medium')
        subject = data.get('subject', '')
        focus_area = data.get('focusArea', 'general')
        student_id = data.get('studentId')
        
        if not text.strip():
            return jsonify({'success': False, 'error': 'Text is required'}), 400
        
        # Calculate word count
        word_count = len(text.split())
        
        # Determine target length based on selection
        if length == 'short':
            target_length = max(50, word_count // 10)
            compression_ratio = 10
        elif length == 'long':
            target_length = max(200, word_count // 3)
            compression_ratio = 33
        else:  # medium
            target_length = max(100, word_count // 4)
            compression_ratio = 25
        
        # Generate AI summary (mock implementation - replace with actual AI)
        summary_text = generate_summary_text(text, length, focus_area)
        key_points = extract_key_points(text, focus_area)
        
        summary_data = {
            'id': 999,  # Would be generated by database
            'originalText': text[:500] + '...' if len(text) > 500 else text,
            'originalLength': word_count,
            'summaryLength': target_length,
            'compressionRatio': f'{compression_ratio}%',
            'summary': summary_text,
            'keyPoints': key_points,
            'readingTime': f'{max(1, target_length // 200)} minute{"s" if target_length // 200 > 1 else ""}',
            'difficulty': determine_difficulty(text),
            'subject': subject or 'General',
            'focusArea': focus_area,
            'createdAt': datetime.now().isoformat(),
            'studentId': student_id
        }
        
        # TODO: Save to database
        # save_summary_to_db(summary_data)
        
        return jsonify({'success': True, 'data': summary_data})
        
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

@student_ai_bp.route('/ai-tools/summaries/<int:student_id>', methods=['GET'])
def get_student_summaries(student_id):
    try:
        # No demo data; return empty until persistence is implemented
        return jsonify({'success': True, 'data': []})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

# Vocabulary Generator Routes
@student_ai_bp.route('/ai-tools/vocabulary-list', methods=['POST'])
def generate_vocabulary_list():
    try:
        data = request.get_json()
        source = data.get('source', 'topic')  # 'topic' or 'text'
        topic = data.get('topic', '')
        text = data.get('text', '')
        subject = data.get('subject', '')
        level = data.get('level', 'intermediate')
        count = data.get('count', 20)
        student_id = data.get('studentId')
        
        if source == 'topic' and not topic:
            return jsonify({'success': False, 'error': 'Topic is required'}), 400
        elif source == 'text' and not text:
            return jsonify({'success': False, 'error': 'Text is required'}), 400
        
        # Generate vocabulary list (mock implementation)
        vocabulary_words = generate_vocabulary_words(source, topic, text, subject, level, count)
        
        # Categorize by difficulty
        categories = {
            'Beginner': len([w for w in vocabulary_words if w['difficulty'] == 'Beginner']),
            'Intermediate': len([w for w in vocabulary_words if w['difficulty'] == 'Intermediate']),
            'Advanced': len([w for w in vocabulary_words if w['difficulty'] == 'Advanced'])
        }
        
        vocab_data = {
            'id': 999,  # Would be generated by database
            'source': topic if source == 'topic' else 'Custom Text',
            'subject': subject,
            'level': level,
            'totalWords': len(vocabulary_words),
            'words': vocabulary_words,
            'categories': categories,
            'createdAt': datetime.now().isoformat(),
            'studentId': student_id
        }
        
        # TODO: Save to database
        # save_vocabulary_to_db(vocab_data)
        
        return jsonify({'success': True, 'data': vocab_data})
        
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

@student_ai_bp.route('/ai-tools/vocabulary-lists/<int:student_id>', methods=['GET'])
def get_student_vocabulary_lists(student_id):
    try:
        # No demo data; return empty until persistence is implemented
        return jsonify({'success': True, 'data': []})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

# Language Learning Tutor Routes
@student_ai_bp.route('/ai-tools/language-lesson', methods=['POST'])
def generate_language_lesson():
    try:
        data = request.get_json()
        language = data.get('language', 'English')
        level = data.get('level', 'intermediate')
        topic = data.get('topic', '')
        lesson_type = data.get('lessonType', 'general')
        student_id = data.get('studentId')
        
        if not topic:
            return jsonify({'success': False, 'error': 'Topic is required'}), 400
        
        # Generate language lesson (mock implementation)
        lesson_data = {
            'id': 999,
            'title': f'{language} Lesson: {topic}',
            'language': language,
            'level': level,
            'topic': topic,
            'lessonType': lesson_type,
            'duration': '45 minutes',
            'objectives': [
                f'Students will understand key {topic.lower()} concepts in {language}',
                f'Students will practice {topic.lower()} vocabulary and usage',
                'Students will demonstrate comprehension through exercises'
            ],
            'vocabulary': generate_language_vocabulary(language, topic, level),
            'grammar': generate_grammar_points(language, topic, level),
            'activities': [
                {
                    'type': 'warm-up',
                    'title': 'Vocabulary Introduction',
                    'duration': '10 minutes',
                    'description': f'Introduce new {topic} vocabulary with visual aids and pronunciation practice'
                },
                {
                    'type': 'practice',
                    'title': 'Guided Practice',
                    'duration': '20 minutes',
                    'description': 'Practice new concepts with interactive exercises and teacher guidance'
                },
                {
                    'type': 'production',
                    'title': 'Speaking Practice',
                    'duration': '10 minutes',
                    'description': 'Students use new vocabulary in conversations and role-plays'
                },
                {
                    'type': 'assessment',
                    'title': 'Quick Assessment',
                    'duration': '5 minutes',
                    'description': 'Check understanding with quick comprehension questions'
                }
            ],
            'exercises': generate_language_exercises(language, topic, level),
            'assessment': {
                'formative': ['Observation during activities', 'Pronunciation checks', 'Vocabulary usage'],
                'summative': ['End-of-lesson quiz', 'Speaking assessment', 'Written exercise']
            },
            'homework': [
                f'Practice new {topic} vocabulary with flashcards',
                'Complete workbook exercises pages 15-17',
                f'Write 5 sentences using new {topic} words'
            ],
            'createdAt': datetime.now().isoformat(),
            'studentId': student_id
        }
        
        # TODO: Save to database
        return jsonify({'success': True, 'data': lesson_data})
        
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

# Career Counselor Routes
@student_ai_bp.route('/ai-tools/career-assessment', methods=['POST'])
def generate_career_assessment():
    try:
        data = request.get_json()
        interests = data.get('interests', [])
        subjects = data.get('subjects', [])
        skills = data.get('skills', [])
        grade_level = data.get('gradeLevel', '')
        student_id = data.get('studentId')
        
        # Generate career recommendations (mock implementation)
        career_data = {
            'id': 999,
            'studentId': student_id,
            'gradeLevel': grade_level,
            'assessmentDate': datetime.now().isoformat(),
            'interests': interests,
            'strongSubjects': subjects,
            'skills': skills,
            'recommendations': generate_career_recommendations(interests, subjects, skills),
            'educationPaths': generate_education_paths(subjects, grade_level),
            'nextSteps': [
                'Research recommended career fields in detail',
                'Talk to professionals in fields of interest',
                'Consider relevant extracurricular activities',
                'Plan course selections for next academic year',
                'Explore internship or shadowing opportunities'
            ],
            'resources': [
                {
                    'type': 'website',
                    'title': 'Uganda Career Guidance Portal',
                    'url': 'https://careers.ug',
                    'description': 'Comprehensive career information for Ugandan students'
                },
                {
                    'type': 'book',
                    'title': 'Career Choices for East African Students',
                    'description': 'Guide to career paths and requirements in East Africa'
                }
            ]
        }
        
        # TODO: Save to database
        return jsonify({'success': True, 'data': career_data})
        
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

@student_ai_bp.route('/ai-tools/career-info/<career_field>', methods=['GET'])
def get_career_information(career_field):
    try:
        # Mock career information
        career_info = {
            'field': career_field,
            'description': f'Detailed information about {career_field} career field',
            'requiredSubjects': ['Mathematics', 'English', 'Science'],
            'universityPrograms': [
                f'Bachelor of {career_field}',
                f'Diploma in {career_field} Studies'
            ],
            'jobOpportunities': [
                f'{career_field} Specialist',
                f'Senior {career_field} Officer',
                f'{career_field} Consultant'
            ],
            'salaryRange': 'UGX 800,000 - 3,500,000 per month',
            'workEnvironment': f'Typical {career_field} work environment description',
            'growthProspects': 'Excellent growth opportunities in Uganda and East Africa'
        }
        
        return jsonify({'success': True, 'data': career_info})
        
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500

# Helper Functions
def generate_summary_text(text, length, focus_area):
    """Generate AI summary text (mock implementation)"""
    if focus_area == 'key-concepts':
        return "This summary focuses on the key concepts and main ideas from the original text. It highlights the most important theoretical frameworks and fundamental principles discussed."
    elif focus_area == 'study-notes':
        return "These study notes summarize the essential information for exam preparation. Key facts, definitions, and important details are emphasized for effective revision."
    elif focus_area == 'exam-prep':
        return "This exam-focused summary highlights testable content and important points likely to appear in assessments. Critical information is organized for efficient study."
    else:
        return "This general summary captures the main points and essential information from the original text, providing a comprehensive overview of the key topics discussed."

def extract_key_points(text, focus_area):
    """Extract key points from text (mock implementation)"""
    return [
        "Primary concept or main idea identified in the text",
        "Important supporting details and evidence presented",
        "Key conclusions and implications drawn from the content",
        "Relevant examples and practical applications mentioned"
    ]

def determine_difficulty(text):
    """Determine text difficulty level (mock implementation)"""
    word_count = len(text.split())
    avg_word_length = sum(len(word) for word in text.split()) / word_count if word_count > 0 else 0
    
    if avg_word_length < 5:
        return "Beginner"
    elif avg_word_length < 7:
        return "Intermediate"
    else:
        return "Advanced"

def generate_vocabulary_words(source, topic, text, subject, level, count):
    """Generate vocabulary words (mock implementation)"""
    sample_words = [
        {'word': 'Photosynthesis', 'definition': 'The process by which plants make food using sunlight', 'difficulty': 'Advanced', 'usage': 'Plants use photosynthesis to convert sunlight into energy.', 'partOfSpeech': 'noun'},
        {'word': 'Chlorophyll', 'definition': 'The green pigment in plants that captures light energy', 'difficulty': 'Intermediate', 'usage': 'Chlorophyll gives leaves their green color.', 'partOfSpeech': 'noun'},
        {'word': 'Glucose', 'definition': 'A simple sugar produced during photosynthesis', 'difficulty': 'Intermediate', 'usage': 'Glucose is the main product of photosynthesis.', 'partOfSpeech': 'noun'},
        {'word': 'Stomata', 'definition': 'Small pores on leaves that allow gas exchange', 'difficulty': 'Advanced', 'usage': 'Carbon dioxide enters the plant through stomata.', 'partOfSpeech': 'noun'},
        {'word': 'Respiration', 'definition': 'The process of breaking down glucose to release energy', 'difficulty': 'Intermediate', 'usage': 'Cellular respiration occurs in all living organisms.', 'partOfSpeech': 'noun'},
        {'word': 'Organism', 'definition': 'A living being such as a plant or animal', 'difficulty': 'Beginner', 'usage': 'Every organism needs energy to survive.', 'partOfSpeech': 'noun'},
        {'word': 'Ecosystem', 'definition': 'A community of living and non-living things in an environment', 'difficulty': 'Intermediate', 'usage': 'The forest ecosystem includes trees, animals, and soil.', 'partOfSpeech': 'noun'},
        {'word': 'Biodiversity', 'definition': 'The variety of life in an ecosystem', 'difficulty': 'Advanced', 'usage': 'Tropical rainforests have high biodiversity.', 'partOfSpeech': 'noun'}
    ]
    
    # Filter by level if specified
    if level != 'mixed':
        level_map = {'beginner': 'Beginner', 'intermediate': 'Intermediate', 'advanced': 'Advanced'}
        target_level = level_map.get(level, 'Intermediate')
        filtered_words = [w for w in sample_words if w['difficulty'] == target_level]
        if filtered_words:
            sample_words = filtered_words
    
    # Return requested number of words
    return sample_words[:min(count, len(sample_words))]

def generate_language_vocabulary(language, topic, level):
    """Generate language-specific vocabulary (mock implementation)"""
    return [
        {'word': 'hello', 'translation': 'greeting', 'pronunciation': '/həˈloʊ/', 'usage': 'Hello, how are you?'},
        {'word': 'thank you', 'translation': 'expression of gratitude', 'pronunciation': '/θæŋk juː/', 'usage': 'Thank you for your help.'},
        {'word': 'please', 'translation': 'polite request word', 'pronunciation': '/pliːz/', 'usage': 'Please pass the salt.'}
    ]

def generate_grammar_points(language, topic, level):
    """Generate grammar points (mock implementation)"""
    return [
        {'rule': 'Present Simple Tense', 'explanation': 'Used for habits and general truths', 'examples': ['I study English.', 'She works every day.']},
        {'rule': 'Articles (a, an, the)', 'explanation': 'Used before nouns to specify or generalize', 'examples': ['a book', 'an apple', 'the teacher']}
    ]

def generate_language_exercises(language, topic, level):
    """Generate language exercises (mock implementation)"""
    return [
        {
            'type': 'fill-in-the-blank',
            'instruction': 'Complete the sentences with the correct word',
            'questions': [
                {'question': 'I _____ to school every day.', 'answer': 'go', 'options': ['go', 'goes', 'going']},
                {'question': 'She _____ a book.', 'answer': 'reads', 'options': ['read', 'reads', 'reading']}
            ]
        },
        {
            'type': 'translation',
            'instruction': 'Translate these sentences',
            'questions': [
                {'english': 'Good morning', 'translation': 'Translation would go here'},
                {'english': 'How are you?', 'translation': 'Translation would go here'}
            ]
        }
    ]

def generate_career_recommendations(interests, subjects, skills):
    """Generate career recommendations (mock implementation)"""
    return [
        {
            'career': 'Software Engineer',
            'match': 95,
            'description': 'Design and develop computer software and applications',
            'requiredSubjects': ['Mathematics', 'Physics', 'Computer Science'],
            'skills': ['Problem-solving', 'Logical thinking', 'Programming'],
            'education': 'Bachelor\'s degree in Computer Science or related field',
            'prospects': 'Excellent job opportunities in Uganda and internationally'
        },
        {
            'career': 'Medical Doctor',
            'match': 88,
            'description': 'Diagnose and treat illnesses and injuries',
            'requiredSubjects': ['Biology', 'Chemistry', 'Physics', 'Mathematics'],
            'skills': ['Analytical thinking', 'Communication', 'Empathy'],
            'education': 'Bachelor of Medicine and Bachelor of Surgery (MBChB)',
            'prospects': 'High demand for medical professionals in Uganda'
        },
        {
            'career': 'Environmental Scientist',
            'match': 82,
            'description': 'Study environmental problems and develop solutions',
            'requiredSubjects': ['Biology', 'Chemistry', 'Geography'],
            'skills': ['Research', 'Data analysis', 'Critical thinking'],
            'education': 'Bachelor\'s degree in Environmental Science or related field',
            'prospects': 'Growing field with increasing environmental awareness'
        }
    ]

def generate_education_paths(subjects, grade_level):
    """Generate education path recommendations (mock implementation)"""
    return [
        {
            'path': 'Science Track',
            'description': 'Focus on mathematics, sciences, and technology',
            'subjects': ['Mathematics', 'Physics', 'Chemistry', 'Biology'],
            'universities': ['Makerere University', 'Mbarara University', 'Gulu University'],
            'careers': ['Engineer', 'Doctor', 'Scientist', 'Pharmacist']
        },
        {
            'path': 'Arts Track',
            'description': 'Focus on languages, humanities, and social sciences',
            'subjects': ['English', 'Literature', 'History', 'Geography'],
            'universities': ['Makerere University', 'Kyambogo University', 'Islamic University'],
            'careers': ['Lawyer', 'Teacher', 'Journalist', 'Social Worker']
        }
    ]
